In [17]:
import open3d as o3d
import numpy as np

### Read and Visualize PointCloud Data

In [8]:

#pcd = o3d.io.read_point_cloud("Data/PCDPointCloud/fragment.pcd")
ply_data = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_data.path)
print(pcd)
o3d.visualization.draw_geometries([pcd])

PointCloud with 196133 points.


### Voxel Downsampling

In [14]:
down_sampled_pcd = pcd.voxel_down_sample(voxel_size=0.05)
print(down_sampled_pcd)
o3d.visualization.draw_geometries([down_sampled_pcd])

PointCloud with 4718 points.


### Vertex normal estimation

In [16]:
down_sampled_pcd.estimate_normals(
    search_param = o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
)
print(down_sampled_pcd)
o3d.visualization.draw_geometries([down_sampled_pcd], point_show_normal=True)

PointCloud with 4718 points.


In [21]:
print(np.asarray(down_sampled_pcd.normals)[:20, :])

[[ 8.56415744e-01  1.69301342e-02 -5.16009150e-01]
 [-3.10071169e-01  3.92564590e-02 -9.49902522e-01]
 [-2.21066308e-01  2.07235365e-07 -9.75258780e-01]
 [-2.65577574e-01 -1.84601949e-01 -9.46250851e-01]
 [-7.91944115e-01 -2.92017206e-02 -6.09894891e-01]
 [-8.84912237e-02 -9.89400811e-01  1.15131831e-01]
 [ 6.28492508e-01 -6.12988948e-01 -4.78791935e-01]
 [ 7.28260110e-01 -4.73518839e-01 -4.95395924e-01]
 [-5.07368635e-03 -9.99572767e-01 -2.87844085e-02]
 [ 3.49295119e-01  1.16948013e-02 -9.36939780e-01]
 [ 9.63879057e-01 -1.93817972e-02 -2.65634166e-01]
 [-7.73339493e-02 -9.70899754e-01 -2.26656409e-01]
 [-1.87480649e-01 -1.40127186e-02 -9.82168341e-01]
 [-6.29023298e-01  2.17802117e-01 -7.46251920e-01]
 [-2.57274133e-01 -5.88119924e-01 -7.66762659e-01]
 [-1.40334733e-02 -9.99890756e-01 -4.64078965e-03]
 [-2.92329662e-01 -4.67586060e-01 -8.34210193e-01]
 [-4.05219839e-01  2.98790678e-01 -8.64014475e-01]
 [-2.91300296e-01  4.39182465e-02 -9.55623004e-01]
 [-3.50554292e-01 -5.02596961e-

### Crop Point Cloud